//! Emitter for the compact hoi4yaml interchange format.

#[allow(unused_imports)]
use crate::*;

pub(crate) fn cmd_emit_hoi4yaml(args: &[String]) -> Result<(), String> {
    let map = parse_args(args);
    let input = require_value(&map, "input")?;
    let tag = value(&map, "tag").unwrap_or("TAG");
    let prefix = value(&map, "prefix").unwrap_or("mod");
    let text = read_utf8_lossy(&normalize_path(&input)?)?;
    let kind = emit_hoi4yaml_kind(value(&map, "kind"), &text)?;
    let yaml = emit_hoi4yaml(&text, kind, tag, prefix);
    write_or_print(&yaml, value(&map, "output"))
}

#[derive(Clone, Copy)]
pub(crate) enum EmitHoi4YamlKind {
    FocusLayout,
    FeatureCards,
    EventCards,
}

pub(crate) fn emit_hoi4yaml_kind(
    explicit: Option<&str>,
    text: &str,
) -> Result<EmitHoi4YamlKind, String> {
    if let Some(kind) = explicit {
        return match kind {
            "focus" | "focus-layout" | "focus_tree" | "national-focus" => {
                Ok(EmitHoi4YamlKind::FocusLayout)
            }
            "feature" | "features" | "feature-cards" | "decision-idea-cards" => {
                Ok(EmitHoi4YamlKind::FeatureCards)
            }
            "event" | "events" | "event-cards" => Ok(EmitHoi4YamlKind::EventCards),
            other => Err(format!("unsupported emit-hoi4yaml kind: {other}")),
        };
    }
    if !parse_cards(text, &["事件"]).is_empty() {
        Ok(EmitHoi4YamlKind::EventCards)
    } else if !parse_cards(text, FEATURE_CARD_HEADERS).is_empty() {
        Ok(EmitHoi4YamlKind::FeatureCards)
    } else {
        Ok(EmitHoi4YamlKind::FocusLayout)
    }
}

pub(crate) fn emit_hoi4yaml(text: &str, kind: EmitHoi4YamlKind, tag: &str, prefix: &str) -> String {
    let mut out = String::new();
    out.push_str("# Generated by hoi4skill emit-hoi4yaml.\n");
    out.push_str("# Optional advanced backend commands:\n");
    out.push_str("#   hoi4yaml mod.yaml --check\n");
    out.push_str("#   hoi4yaml mod.yaml\n\n");
    match kind {
        EmitHoi4YamlKind::FocusLayout => emit_focus_layout_hoi4yaml(&mut out, text, tag, prefix),
        EmitHoi4YamlKind::FeatureCards => emit_feature_cards_hoi4yaml(&mut out, text, tag, prefix),
        EmitHoi4YamlKind::EventCards => emit_event_cards_hoi4yaml(&mut out, text, tag, prefix),
    }
    out
}

pub(crate) fn emit_focus_layout_hoi4yaml(out: &mut String, text: &str, tag: &str, prefix: &str) {
    let layout = parse_focus_layout(text, tag, prefix);
    out.push_str("national_focus:\n");
    out.push_str(&format!(
        "  - _file: {}\n",
        yaml_string(&format!("{prefix}_{tag}_focus"))
    ));
    out.push_str("    focus_tree:\n");
    out.push_str(&format!("      id: {}\n", yaml_string(&layout.tree_id)));
    out.push_str("      country:\n");
    out.push_str("        factor: 0\n");
    out.push_str("        modifier:\n");
    out.push_str("          add: 10\n");
    out.push_str(&format!("          tag: {}\n", yaml_string(tag)));
    out.push_str("      focus:\n");
    for focus in &layout.focuses {
        out.push_str(&format!("        - id: {}\n", yaml_string(&focus.id)));
        out.push_str(&format!(
            "          icon: {}\n",
            yaml_string(choose_focus_icon(&focus.title))
        ));
        out.push_str(&format!("          x: {}\n", focus.x));
        out.push_str(&format!("          y: {}\n", focus.y));
        out.push_str("          cost: 10\n");
        emit_yaml_string_or_list(out, "          ", "prereq", &focus.prerequisite);
        emit_yaml_string_or_list(
            out,
            "          ",
            "mutually_exclusive",
            &focus.mutually_exclusive,
        );
        out.push_str("          reward: {}\n");
        out.push_str("          ai_will_do: 1\n");
    }
    let loc_entries = layout
        .focuses
        .iter()
        .flat_map(|focus| {
            [
                (focus.id.clone(), focus.title.clone()),
                (
                    format!("{}_desc", focus.id),
                    fallback_focus_description(focus),
                ),
            ]
        })
        .collect::<BTreeMap<_, _>>();
    emit_localisation_yaml(out, &loc_entries);
}

pub(crate) fn emit_feature_cards_hoi4yaml(out: &mut String, text: &str, tag: &str, prefix: &str) {
    let cards = parse_cards(text, FEATURE_CARD_HEADERS);
    let mut decision_categories: BTreeMap<String, String> = BTreeMap::new();
    let mut decisions = Vec::new();
    let mut ideas = Vec::new();
    let mut technologies = Vec::new();
    let mut guis = Vec::new();
    let mut scripted_effects = Vec::new();
    let mut scripted_triggers = Vec::new();
    let mut state_effects = Vec::new();
    let mut loc_entries = BTreeMap::new();

    for (idx, card) in cards.iter().enumerate() {
        match card.kind.as_str() {
            "决议" => {
                let target = card.fields.get("目标").map(String::as_str).unwrap_or(tag);
                let category_title = card
                    .fields
                    .get("分类")
                    .map(String::as_str)
                    .unwrap_or("国家决议");
                let category_id = format!(
                    "{}_{}",
                    prefix,
                    slugify(category_title, &format!("category_{idx}"))
                );
                let decision_id = feature_card_id(card, prefix, "decision", idx);
                decision_categories
                    .entry(category_id.clone())
                    .or_insert_with(|| target.to_string());
                decisions.push((
                    card,
                    category_id.clone(),
                    decision_id.clone(),
                    target.to_string(),
                ));
                loc_entries.insert(category_id, category_title.to_string());
                loc_entries.insert(decision_id.clone(), card.title.clone());
                loc_entries.insert(
                    format!("{decision_id}_desc"),
                    card.fields
                        .get("描述")
                        .cloned()
                        .unwrap_or_else(|| fallback_decision_description(card)),
                );
            }
            "民族精神" => {
                let idea_id = feature_card_id(card, prefix, "idea", idx);
                ideas.push((card, idea_id.clone()));
                loc_entries.insert(idea_id.clone(), card.title.clone());
                loc_entries.insert(
                    format!("{idea_id}_desc"),
                    card.fields
                        .get("描述")
                        .cloned()
                        .unwrap_or_else(|| fallback_idea_description(card)),
                );
            }
            kind if is_technology_card(kind) => {
                let target = card.fields.get("目标").map(String::as_str).unwrap_or(tag);
                let technology_id = feature_card_id(card, prefix, "technology", idx);
                technologies.push((card, technology_id.clone(), target.to_string()));
                loc_entries.insert(technology_id.clone(), card.title.clone());
                loc_entries.insert(
                    format!("{technology_id}_desc"),
                    card.fields
                        .get("描述")
                        .cloned()
                        .unwrap_or_else(|| format!("{}是一项独有技术。", card.title)),
                );
            }
            kind if is_gui_card(kind) => {
                let target = card.fields.get("目标").map(String::as_str).unwrap_or(tag);
                let gui_id = feature_card_id(card, prefix, "gui", idx);
                guis.push((card, gui_id.clone(), target.to_string()));
                loc_entries.insert(gui_id.clone(), card.title.clone());
                loc_entries.insert(
                    format!("{gui_id}_desc"),
                    card.fields
                        .get("描述")
                        .or_else(|| card.fields.get("用途"))
                        .cloned()
                        .unwrap_or_else(|| format!("{}界面。", card.title)),
                );
            }
            kind if is_scripted_effect_card(kind) => {
                let effect_id = feature_card_id(card, prefix, "scripted_effect", idx);
                scripted_effects.push((card, effect_id));
            }
            kind if is_scripted_trigger_card(kind) => {
                let trigger_id = feature_card_id(card, prefix, "scripted_trigger", idx);
                scripted_triggers.push((card, trigger_id));
            }
            kind if is_state_effect_card(kind) => {
                let target = card.fields.get("目标").map(String::as_str).unwrap_or(tag);
                let effect_id = feature_card_id(card, prefix, "state_effect", idx);
                state_effects.push((card, effect_id, target.to_string()));
            }
            _ => {}
        }
    }

    if !decision_categories.is_empty() {
        out.push_str("decisions_categories:\n");
        out.push_str(&format!(
            "  - _file: {}\n",
            yaml_string(&format!("{prefix}_categories"))
        ));
        for (category_id, target) in &decision_categories {
            out.push_str(&format!("    {}:\n", yaml_key(category_id)));
            out.push_str("      icon: \"GFX_decision_generic_political_reform\"\n");
            out.push_str("      picture: \"GFX_decision_category_generic_political_reform\"\n");
            out.push_str("      allowed:\n");
            out.push_str(&format!("        original_tag: {}\n", yaml_string(target)));
            out.push_str("      visible:\n");
            out.push_str(&format!("        tag: {}\n", yaml_string(target)));
            out.push_str("      visible_when_empty: true\n");
        }
        out.push('\n');
    }

    if !decisions.is_empty() {
        out.push_str("decisions:\n");
        out.push_str(&format!(
            "  - _file: {}\n",
            yaml_string(&format!("{prefix}_decisions"))
        ));
        for (card, category_id, decision_id, target) in decisions {
            emit_decision_card_hoi4yaml(out, card, &category_id, &decision_id, &target);
        }
        out.push('\n');
    }

    if !ideas.is_empty() {
        out.push_str("ideas:\n");
        out.push_str(&format!(
            "  - _file: {}\n",
            yaml_string(&format!("{prefix}_ideas"))
        ));
        out.push_str("    _category: \"country\"\n");
        for (card, idea_id) in ideas {
            emit_idea_card_hoi4yaml(out, card, &idea_id);
        }
        out.push('\n');
    }

    if !technologies.is_empty() {
        out.push_str("technologies:\n");
        out.push_str(&format!(
            "  - _file: {}\n",
            yaml_string(&format!("{prefix}_technologies"))
        ));
        for (card, technology_id, target) in technologies {
            emit_technology_card_hoi4yaml(out, card, &technology_id, &target);
        }
        out.push('\n');
    }

    if !guis.is_empty() {
        out.push_str("scripted_guis:\n");
        out.push_str(&format!(
            "  - _file: {}\n",
            yaml_string(&format!("{prefix}_scripted_guis"))
        ));
        for (card, gui_id, target) in &guis {
            emit_scripted_gui_card_hoi4yaml(out, card, gui_id, target);
        }
        out.push('\n');
        out.push_str("interface:\n");
        out.push_str(&format!("  - _file: {}\n", yaml_string(prefix)));
        out.push_str("    guiTypes:\n");
        for (card, gui_id, _) in guis {
            emit_interface_gui_card_hoi4yaml(out, card, &gui_id);
        }
        out.push('\n');
    }

    if !scripted_effects.is_empty() || !state_effects.is_empty() {
        out.push_str("scripted_effects:\n");
        if !scripted_effects.is_empty() {
            out.push_str(&format!(
                "  - _file: {}\n",
                yaml_string(&format!("{prefix}_scripted_effects"))
            ));
            for (card, effect_id) in scripted_effects {
                emit_scripted_effect_card_hoi4yaml(out, card, &effect_id);
            }
        }
        if !state_effects.is_empty() {
            out.push_str(&format!(
                "  - _file: {}\n",
                yaml_string(&format!("{prefix}_state_effects"))
            ));
            for (card, effect_id, target) in state_effects {
                emit_state_effect_card_hoi4yaml(out, card, &effect_id, &target);
            }
        }
        out.push('\n');
    }

    if !scripted_triggers.is_empty() {
        out.push_str("scripted_triggers:\n");
        out.push_str(&format!(
            "  - _file: {}\n",
            yaml_string(&format!("{prefix}_scripted_triggers"))
        ));
        for (card, trigger_id) in scripted_triggers {
            emit_scripted_trigger_card_hoi4yaml(out, card, &trigger_id);
        }
        out.push('\n');
    }

    emit_localisation_yaml(out, &loc_entries);
}

pub(crate) fn emit_decision_card_hoi4yaml(
    out: &mut String,
    card: &Card,
    category_id: &str,
    decision_id: &str,
    target: &str,
) {
    let icon = card
        .fields
        .get("图标")
        .map(String::as_str)
        .unwrap_or("generic_political_discourse");
    let cost = card
        .fields
        .get("花费")
        .and_then(|s| parse_int(s))
        .unwrap_or(50);
    let days = card
        .fields
        .get("冷却")
        .or_else(|| card.fields.get("持续"))
        .and_then(|s| parse_int(s));
    let condition = join_existing_fields(&card.fields, &["条件", "可用", "前置", "前置国策"]);
    let suggestions = suggest_common(
        "decision",
        card.fields.get("效果").map(String::as_str).unwrap_or(""),
        None,
        None,
        condition.as_deref(),
        None,
    );
    let trigger_lines = concrete_suggestion_lines(&suggestions, &["trigger"]);
    let (effect_lines, effect_comments) = decision_effect_lines(&suggestions);

    out.push_str(&format!("    {}:\n", yaml_key(category_id)));
    out.push_str(&format!("      {}:\n", yaml_key(decision_id)));
    out.push_str(&format!("        icon: {}\n", yaml_string(icon)));
    out.push_str(&format!("        cost: {cost}\n"));
    if let Some(days) = days {
        out.push_str(&format!("        days_remove: {days}\n"));
    }
    out.push_str("        visible:\n");
    out.push_str(&format!("          tag: {}\n", yaml_string(target)));
    out.push_str("        available:\n");
    if trigger_lines.is_empty() {
        out.push_str("          always: true\n");
    } else {
        emit_hoi4_assignment_lines_as_yaml(out, "          ", &trigger_lines);
    }
    out.push_str("        complete_effect:\n");
    if effect_lines.is_empty() && effect_comments.is_empty() {
        out.push_str("          # TODO: add effects from card text\n");
    }
    emit_hoi4_assignment_lines_as_yaml(out, "          ", &effect_lines);
    for comment in effect_comments {
        emit_yaml_comment(out, "          ", &comment);
    }
    out.push_str("        ai_will_do:\n");
    out.push_str("          factor: 1\n");
}

pub(crate) fn emit_idea_card_hoi4yaml(out: &mut String, card: &Card, idea_id: &str) {
    let picture = card
        .fields
        .get("图标")
        .map(String::as_str)
        .unwrap_or("generic_production_bonus");
    let suggestions = suggest_common(
        "idea",
        card.fields.get("效果").map(String::as_str).unwrap_or(""),
        None,
        None,
        None,
        card.fields.get("移除").map(String::as_str),
    );
    let field_lines = concrete_suggestion_lines(&suggestions, &["idea_field"]);
    let modifier_lines =
        concrete_suggestion_lines(&suggestions, &["idea_modifier", "idea_modifier_candidate"]);
    out.push_str(&format!("    {}:\n", yaml_key(idea_id)));
    out.push_str(&format!("      picture: {}\n", yaml_string(picture)));
    emit_hoi4_assignment_lines_as_yaml(out, "      ", &field_lines);
    out.push_str("      modifier:\n");
    if modifier_lines.is_empty() {
        out.push_str("        # TODO: add idea modifiers from card effects\n");
    } else {
        emit_hoi4_assignment_lines_as_yaml(out, "        ", &modifier_lines);
    }
}

pub(crate) fn emit_technology_card_hoi4yaml(
    out: &mut String,
    card: &Card,
    technology_id: &str,
    target: &str,
) {
    let research_cost = card
        .fields
        .get("花费")
        .or_else(|| card.fields.get("研究花费"))
        .and_then(|s| parse_int(s))
        .unwrap_or(1)
        .max(1);
    let start_year = card
        .fields
        .get("年份")
        .or_else(|| card.fields.get("起始年份"))
        .and_then(|s| parse_int(s))
        .unwrap_or(1936);
    let folder = card
        .fields
        .get("文件夹")
        .or_else(|| card.fields.get("科技文件夹"))
        .map(|value| sanitize_identifier_part(value, "special_folder"))
        .unwrap_or_else(|| "special_forces_folder".to_string());
    out.push_str(&format!("    {}:\n", yaml_key(technology_id)));
    out.push_str(&format!("      research_cost: {research_cost}\n"));
    out.push_str(&format!("      start_year: {start_year}\n"));
    out.push_str("      folder:\n");
    out.push_str(&format!("        name: {}\n", yaml_string(&folder)));
    out.push_str("        position:\n");
    out.push_str("          x: 0\n");
    out.push_str("          y: 0\n");
    out.push_str("      categories:\n");
    for category in technology_categories_from_card(card) {
        out.push_str(&format!("        - {}\n", yaml_string(&category)));
    }
    out.push_str(&format!("      _target: {}\n", yaml_string(target)));
    if let Some(effect) = card.fields.get("效果") {
        emit_yaml_comment(out, "      ", &format!("effect note: {effect}"));
    }
}

pub(crate) fn emit_scripted_gui_card_hoi4yaml(
    out: &mut String,
    card: &Card,
    gui_id: &str,
    target: &str,
) {
    out.push_str(&format!("    {}:\n", yaml_key(gui_id)));
    out.push_str("      context_type: \"country_context\"\n");
    out.push_str(&format!(
        "      window_name: {}\n",
        yaml_string(&format!("{gui_id}_window"))
    ));
    out.push_str("      visible:\n");
    out.push_str(&format!("        tag: {}\n", yaml_string(target)));
    out.push_str("      triggers:\n");
    out.push_str("        always: true\n");
    out.push_str("      effects: {}\n");
    if let Some(effect) = card.fields.get("效果") {
        emit_yaml_comment(out, "      ", &format!("effect note: {effect}"));
    }
}

pub(crate) fn emit_interface_gui_card_hoi4yaml(out: &mut String, card: &Card, gui_id: &str) {
    out.push_str("      - containerWindowType:\n");
    out.push_str(&format!(
        "          name: {}\n",
        yaml_string(&format!("{gui_id}_window"))
    ));
    out.push_str("          position: { x: 0, y: 0 }\n");
    out.push_str("          size: { width: 420, height: 180 }\n");
    out.push_str("          moveable: true\n");
    out.push_str("          title_key: ");
    out.push_str(&yaml_string(gui_id));
    out.push('\n');
    if let Some(body) = card.fields.get("用途").or_else(|| card.fields.get("描述")) {
        emit_yaml_comment(out, "          ", body);
    }
}

pub(crate) fn emit_scripted_effect_card_hoi4yaml(out: &mut String, card: &Card, effect_id: &str) {
    let scope = scripted_helper_scope(card);
    let effect_text =
        join_existing_fields(&card.fields, &["效果", "动作", "内容", "执行"]).unwrap_or_default();
    let suggestions = suggest_common("scripted_effect", &effect_text, None, None, None, None);
    let (effect_lines, effect_comments) = scripted_effect_lines(&suggestions, scope);
    out.push_str(&format!("    {}:\n", yaml_key(effect_id)));
    out.push_str(&format!("      _scope: {}\n", yaml_string(scope)));
    if effect_lines.is_empty() && effect_comments.is_empty() {
        if effect_text.trim().is_empty() {
            out.push_str("      # TODO: add scripted effect body\n");
        } else {
            emit_yaml_comment(out, "      ", &effect_text);
        }
    }
    emit_hoi4_assignment_lines_as_yaml(out, "      ", &effect_lines);
    for comment in effect_comments {
        emit_yaml_comment(out, "      ", &comment);
    }
}

pub(crate) fn emit_state_effect_card_hoi4yaml(
    out: &mut String,
    card: &Card,
    effect_id: &str,
    target: &str,
) {
    let state_target = state_card_target(card);
    let suggestions = state_card_suggestions(card, target);
    let (effect_lines, effect_comments) = state_effect_body_lines(&suggestions);
    out.push_str(&format!("    {}:\n", yaml_key(effect_id)));
    if let Some(state_id) = state_target.id {
        out.push_str(&format!("      _state_id: {state_id}\n"));
    } else {
        out.push_str("      _scope: \"state\"\n");
    }
    if let Some(label) = state_target.label.as_deref() {
        out.push_str(&format!("      _state: {}\n", yaml_string(label)));
    }
    if effect_lines.is_empty() && effect_comments.is_empty() {
        out.push_str("      # TODO: add state effects from card text\n");
    }
    emit_hoi4_assignment_lines_as_yaml(out, "      ", &effect_lines);
    for comment in effect_comments {
        emit_yaml_comment(out, "      ", &comment);
    }
}

pub(crate) fn emit_scripted_trigger_card_hoi4yaml(out: &mut String, card: &Card, trigger_id: &str) {
    let trigger_text = join_existing_fields(
        &card.fields,
        &["条件", "触发", "可用", "可见", "限制", "内容"],
    )
    .unwrap_or_default();
    let suggestions = split_cn_list(&trigger_text)
        .into_iter()
        .flat_map(suggest_trigger)
        .collect::<Vec<_>>();
    let (trigger_lines, trigger_comments) = trigger_lines_and_comments(&suggestions);
    out.push_str(&format!("    {}:\n", yaml_key(trigger_id)));
    if trigger_lines.is_empty() && trigger_comments.is_empty() {
        if trigger_text.trim().is_empty() {
            out.push_str("      # TODO: add scripted trigger body\n");
        } else {
            emit_yaml_comment(out, "      ", &trigger_text);
        }
    }
    emit_hoi4_assignment_lines_as_yaml(out, "      ", &trigger_lines);
    for comment in trigger_comments {
        emit_yaml_comment(out, "      ", &comment);
    }
}

pub(crate) fn emit_event_cards_hoi4yaml(out: &mut String, text: &str, tag: &str, prefix: &str) {
    let cards = parse_cards(text, &["事件"]);
    let event_ids = event_card_numbered_ids(&cards, prefix);
    let mut loc_entries = BTreeMap::new();
    for (card, (_, event_id)) in cards.iter().zip(event_ids.iter()) {
        insert_event_localisation(card, event_id, &mut loc_entries);
    }

    out.push_str("events:\n");
    out.push_str(&format!(
        "  - _file: {}\n",
        yaml_string(&format!("{prefix}_events"))
    ));
    let namespaces = event_ids
        .iter()
        .map(|(namespace, _)| namespace.to_string())
        .collect::<BTreeSet<_>>();
    if namespaces.len() == 1 {
        if let Some(namespace) = namespaces.iter().next() {
            out.push_str(&format!("    _namespace: {}\n", yaml_string(namespace)));
        }
    } else if !namespaces.is_empty() {
        out.push_str("    _namespaces:\n");
        for namespace in namespaces {
            out.push_str(&format!("      - {}\n", yaml_string(&namespace)));
        }
    }
    let mut grouped: BTreeMap<String, Vec<(usize, &Card)>> = BTreeMap::new();
    for (idx, (card, _)) in cards.iter().zip(event_ids.iter()).enumerate() {
        let event_type = normalize_event_type(card.fields.get("类型").map(String::as_str));
        grouped
            .entry(event_type.to_string())
            .or_default()
            .push((idx, card));
    }
    for (event_type, items) in grouped {
        out.push_str(&format!("    {}:\n", yaml_key(&event_type)));
        for (idx, card) in items {
            let (_, event_id) = &event_ids[idx];
            emit_event_card_hoi4yaml(out, card, event_id, tag);
        }
    }
    out.push('\n');
    emit_localisation_yaml(out, &loc_entries);
}

pub(crate) fn emit_event_card_hoi4yaml(out: &mut String, card: &Card, event_id: &str, tag: &str) {
    let picture = card
        .fields
        .get("图片")
        .map(String::as_str)
        .unwrap_or("GFX_report_event_generic");
    let trigger = card.fields.get("触发").or_else(|| card.fields.get("条件"));
    let trigger_lines = trigger
        .map(|text| {
            split_cn_list(text)
                .into_iter()
                .flat_map(suggest_trigger)
                .filter(|suggestion| suggestion.kind == "trigger")
                .filter_map(|suggestion| concrete_suggestion_code(&suggestion))
                .collect::<Vec<_>>()
        })
        .unwrap_or_else(|| vec![format!("tag = {tag}")]);

    out.push_str(&format!("      - id: {}\n", yaml_string(event_id)));
    out.push_str(&format!(
        "        title: {}\n",
        yaml_string(&format!("{event_id}.t"))
    ));
    out.push_str(&format!(
        "        desc: {}\n",
        yaml_string(&format!("{event_id}.d"))
    ));
    out.push_str(&format!("        picture: {}\n", yaml_string(picture)));
    out.push_str("        is_triggered_only: true\n");
    if !trigger_lines.is_empty() {
        out.push_str("        trigger:\n");
        emit_hoi4_assignment_lines_as_yaml(out, "          ", &trigger_lines);
    }
    out.push_str("        option:\n");
    for option in event_options(card) {
        out.push_str(&format!(
            "          - name: {}\n",
            yaml_string(&format!("{event_id}.{}", option.key))
        ));
        if let Some(factor) = parse_int(&option.ai_chance) {
            out.push_str("            ai_chance:\n");
            out.push_str(&format!("              factor: {factor}\n"));
        }
        let suggestions = suggest_common("event", &option.effects, None, None, None, None);
        let (effect_lines, effect_comments) = decision_effect_lines(&suggestions);
        if option.effects.trim().is_empty() && option.hidden_effects.trim().is_empty() {
            out.push_str("            # TODO: add option effects\n");
        }
        emit_hoi4_assignment_lines_as_yaml(out, "            ", &effect_lines);
        for comment in effect_comments {
            emit_yaml_comment(out, "            ", &comment);
        }
        if !option.hidden_effects.trim().is_empty() {
            let hidden_suggestions =
                suggest_common("event", &option.hidden_effects, None, None, None, None);
            let (hidden_lines, hidden_comments) = decision_effect_lines(&hidden_suggestions);
            out.push_str("            hidden_effect:\n");
            if hidden_lines.is_empty() && hidden_comments.is_empty() {
                emit_yaml_comment(out, "              ", &option.hidden_effects);
            }
            emit_hoi4_assignment_lines_as_yaml(out, "              ", &hidden_lines);
            for comment in hidden_comments {
                emit_yaml_comment(out, "              ", &comment);
            }
        }
    }
}

pub(crate) fn emit_yaml_string_or_list(
    out: &mut String,
    indent: &str,
    key: &str,
    values: &[String],
) {
    if values.is_empty() {
        return;
    }
    if values.len() == 1 {
        out.push_str(&format!("{indent}{key}: {}\n", yaml_string(&values[0])));
    } else {
        out.push_str(&format!("{indent}{key}:\n"));
        for value in values {
            out.push_str(&format!("{indent}  - {}\n", yaml_string(value)));
        }
    }
}

pub(crate) fn emit_hoi4_assignment_lines_as_yaml(out: &mut String, indent: &str, lines: &[String]) {
    for line in lines {
        emit_hoi4_assignment_as_yaml(out, indent, line);
    }
}

pub(crate) fn emit_hoi4_assignment_as_yaml(out: &mut String, indent: &str, line: &str) {
    let line = line.trim();
    if line.is_empty() {
        return;
    }
    if line.contains('{') || line.contains('}') || line.contains('\n') {
        emit_yaml_comment(
            out,
            indent,
            &format!("TODO raw HOI4 block: {}", flatten_ws(line)),
        );
        return;
    }
    let Some((key, value)) = line.split_once('=') else {
        emit_yaml_comment(
            out,
            indent,
            &format!("TODO unmapped line: {}", flatten_ws(line)),
        );
        return;
    };
    out.push_str(&format!(
        "{}{}: {}\n",
        indent,
        yaml_key(key.trim()),
        yaml_hoi4_value(value.trim())
    ));
}

pub(crate) fn emit_localisation_yaml(out: &mut String, entries: &BTreeMap<String, String>) {
    if entries.is_empty() {
        return;
    }
    out.push_str("localisation:\n");
    out.push_str("  simp_chinese:\n");
    for (key, value) in entries {
        out.push_str(&format!("    {}: {}\n", yaml_key(key), yaml_string(value)));
    }
}

pub(crate) fn emit_yaml_comment(out: &mut String, indent: &str, comment: &str) {
    for line in flatten_ws(comment).lines() {
        out.push_str(&format!("{indent}# {line}\n"));
    }
}

pub(crate) fn flatten_ws(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

pub(crate) fn yaml_key(key: &str) -> String {
    if !key.is_empty()
        && !key.starts_with('-')
        && key
            .chars()
            .all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '_' | '-' | '.'))
    {
        key.to_string()
    } else {
        yaml_string(key)
    }
}

pub(crate) fn yaml_string(value: &str) -> String {
    json_str(value)
}

pub(crate) fn yaml_hoi4_value(value: &str) -> String {
    if value == "yes" {
        "true".to_string()
    } else if value == "no" {
        "false".to_string()
    } else if value.parse::<i64>().is_ok() || value.parse::<f64>().is_ok() {
        value.to_string()
    } else {
        yaml_string(value)
    }
}
