//! Human-facing command usage text for the CLI.

#[allow(unused_imports)]
use crate::*;

pub(crate) fn print_usage() {
    println!(
        r#"hoi4skill {}

Usage:
  hoi4skill scaffold --name "My Mod" --output "M:\path\mod" [--launcher-file]
  hoi4skill plan-large-mod --text "large alternate-history design" [--name "My Large Mod"] [--acronym MLM] [--language simp_chinese] [--output mod_blueprint.yml]
  hoi4skill plan-large-mod --input design_doc.md [--output mod_blueprint.yml]
  hoi4skill init-large-mod --blueprint mod_blueprint.yml --output "M:\path\large_mod" [--game-root "C:\path\Hearts of Iron IV"] [--launcher-file]
  hoi4skill split-work-packages --blueprint mod_blueprint.yml [--mod-root "M:\path\large_mod"] [--output work_packages]
  hoi4skill generate-work-package --blueprint mod_blueprint.yml --package country_rus --dry-run [--mod-root "M:\path\large_mod"] [--output package_plan.json]
  hoi4skill work-package-start-brief --mod-root "M:\path\large_mod" --package country_rus [--output start_country_rus.md]
  hoi4skill work-package-start-briefs --mod-root "M:\path\large_mod" [--ready-only] [--output-dir .hoi4skill/start_briefs] [--output start_briefs_manifest.json]
  hoi4skill work-package-authoring-pack --mod-root "M:\path\large_mod" --package country_rus [--output-dir .hoi4skill/authoring/country_rus] [--output authoring_manifest.json]
  hoi4skill work-package-claim --mod-root "M:\path\large_mod" --package country_rus --assignee codex-a [--allow-blocked] [--force] [--output claim_country_rus.json]
  hoi4skill work-package-release-claim --mod-root "M:\path\large_mod" --package country_rus --released-by codex-a --reason "handoff reassigned" [--claims-dir .hoi4skill/claims] [--output release_country_rus.json] [--force]
  hoi4skill work-package-claims --mod-root "M:\path\large_mod" [--claims-dir .hoi4skill/claims] [--output claims.json]
  hoi4skill work-package-dispatch-board --mod-root "M:\path\large_mod" [--claims-dir .hoi4skill/claims] [--output dispatch_board.md]
  hoi4skill large-mod-dispatch-gate --mod-root "M:\path\large_mod" [--claims-dir .hoi4skill/claims] [--allow-unclaimed] [--output dispatch_gate.json]
  hoi4skill work-package-status --mod-root "M:\path\large_mod" [--package country_rus] [--report custom_report.json] [--output .hoi4skill/work_package_status.json]
  hoi4skill check-work-package-boundary --mod-root "M:\path\large_mod" --package country_rus --changed common/national_focus/RUS.txt [--changed-file changed.txt] [--strict-names] [--output boundary.json]
  hoi4skill large-mod-ci-plan --mod-root "M:\path\large_mod" [--game-root "C:\path\Hearts of Iron IV"] [--package country_rus] [--strict-names] [--output ci_plan.json]
  hoi4skill large-mod-release-gate --mod-root "M:\path\large_mod" [--report custom_report.json] [--output release_gate.json]
  hoi4skill identify-work-packages --mod-root "M:\path\large_mod" --changed events/rus_events.txt [--changed-file changed.txt] [--strict-names] [--output changed_work_packages.json]
  hoi4skill split-changed-work-packages --mod-root "M:\path\large_mod" --changed events/rus_events.txt [--changed-file changed.txt] [--strict-names] [--output-dir .hoi4skill] [--output split_changed.json]
  hoi4skill work-package-readiness --mod-root "M:\path\large_mod" [--package country_rus] [--output readiness.json]
  hoi4skill work-package-handoff --mod-root "M:\path\large_mod" --package country_rus [--output handoff_country_rus.md]
  hoi4skill work-package-review-checklist --mod-root "M:\path\large_mod" --package country_rus [--claims-dir .hoi4skill/claims] [--output review_checklist_country_rus.md]
  hoi4skill work-package-merge-gate --mod-root "M:\path\large_mod" --package country_rus [--claims-dir .hoi4skill/claims] [--output merge_gate_country_rus.json]
  hoi4skill work-package-merge-gates --mod-root "M:\path\large_mod" [--claims-dir .hoi4skill/claims] [--output-dir .hoi4skill/merge_gates] [--output merge_gates_manifest.json]
  hoi4skill work-package-playtest-report --mod-root "M:\path\large_mod" --package country_rus --result passed|needs_review [--summary "tested focus/event loop"] [--finding "issue"] [--evidence "save/path"] [--output playtest_country_rus.json]
  hoi4skill large-mod-merge-gate --mod-root "M:\path\large_mod" [--claims-dir .hoi4skill/claims] [--output merge_gate.json]
  hoi4skill large-mod-review-queue --mod-root "M:\path\large_mod" [--claims-dir .hoi4skill/claims] [--output review_queue.json]
  hoi4skill large-mod-ownership-map --mod-root "M:\path\large_mod" [--output ownership_map.json]
  hoi4skill large-mod-dependency-graph --mod-root "M:\path\large_mod" [--output dependency_graph.json]
  hoi4skill large-mod-milestone-plan --mod-root "M:\path\large_mod" [--output milestone_plan.json]
  hoi4skill large-mod-execution-queue --mod-root "M:\path\large_mod" [--output execution_queue.json]
  hoi4skill large-mod-dashboard --mod-root "M:\path\large_mod" [--report custom_report.json] [--output dashboard.md]
  hoi4skill large-mod-next-actions --mod-root "M:\path\large_mod" [--report custom_report.json] [--output next_actions.json]
  hoi4skill large-mod-production-snapshot --mod-root "M:\path\large_mod" [--claims-dir .hoi4skill/claims] [--report custom_report.json] [--output production_snapshot.json]
  hoi4skill large-mod-production-brief --mod-root "M:\path\large_mod" [--claims-dir .hoi4skill/claims] [--report custom_report.json] [--output production_brief.md]
  hoi4skill large-mod-fix-queue --mod-root "M:\path\large_mod" [--report error_log_report.json] [--output fix_queue.json]
  hoi4skill large-mod-regression-plan --mod-root "M:\path\large_mod" [--report error_log_report.json] [--output regression_plan.json]
  hoi4skill large-mod-regression-gate --mod-root "M:\path\large_mod" [--plan regression_plan.json] [--report error_log_report.json] [--output regression_gate.json]
  hoi4skill large-mod-regression-brief --mod-root "M:\path\large_mod" [--plan regression_plan.json] [--report error_log_report.json] [--output regression_brief.md]
  hoi4skill large-mod-risk-register --mod-root "M:\path\large_mod" [--claims-dir .hoi4skill/claims] [--report custom_report.json] [--output risk_register.json]
  hoi4skill large-mod-evidence-pack --mod-root "M:\path\large_mod" [--report custom_report.json] [--output evidence_pack.json]
  hoi4skill large-mod-review-brief --mod-root "M:\path\large_mod" [--report custom_report.json] [--output review_brief.md]
  hoi4skill large-mod-release-bundle --mod-root "M:\path\large_mod" [--report custom_report.json] [--output release_bundle.json]
  hoi4skill large-mod-release-brief --mod-root "M:\path\large_mod" [--report custom_report.json] [--output release_brief.md]
  hoi4skill large-mod-release-notes --mod-root "M:\path\large_mod" [--output release_notes.md]
  hoi4skill large-mod-playtest-plan --mod-root "M:\path\large_mod" [--output playtest_plan.json]
  hoi4skill large-mod-playtest-gate --mod-root "M:\path\large_mod" [--report playtest_country_rus.json] [--output playtest_gate.json]
  hoi4skill large-mod-playtest-brief --mod-root "M:\path\large_mod" [--report playtest_country_rus.json] [--output playtest_brief.md]
  hoi4skill detect-hoi4-path [--hoi4-path "C:\path\Hearts of Iron IV"] [--output hoi4_path.json]
  hoi4skill validate "M:\path\mod" [--request "literal user request"]
  hoi4skill validate "M:\path\mod" --game-root "C:\path\Hearts of Iron IV" [--mod-path "M:\path\dependency.mod"] [--request "literal user request"] [--strict-code-index|--final-check]
  hoi4skill validate "M:\path\mod" [--baseline baseline.json] [--changed-only --changed common/national_focus/RUS.txt] [--output validation.json]
  hoi4skill validate "M:\path\mod" --text-source "M:\path\user_input.txt" [--expect-title "Exact title"]
  hoi4skill build-game-index --game-root "C:\path\Hearts of Iron IV" [--mod-path "M:\path\dependency.mod"] [--output game_index.json]
  hoi4skill code-catalog --game-root "C:\path\Hearts of Iron IV" [--mod-path "M:\path\dependency.mod"] [--max-items 200] [--output code_catalog.json]
  hoi4skill check-code-symbol --game-root "C:\path\Hearts of Iron IV" --symbol add_political_power [--kind effect|trigger|modifier|resource_id|map_id] [--mod-path "M:\path\dependency.mod"] [--output symbol_check.json]
  hoi4skill compile-intent --text "llm：战争正当化 = -10%" [--kind idea|effect|trigger|state-effect|auto] [--game-root "C:\path\Hearts of Iron IV"] [--mod-path "M:\path\dependency.mod"] [--strict-code-index|--final-check] [--output intent.json]
  hoi4skill check-text-alignment --mod-root "M:\path\mod" --input "M:\path\user_input.txt" [--expect-title "Exact title"] [--output text_alignment.json]
  hoi4skill clausewitz-reference [--game-root "C:\path\Hearts of Iron IV"] [--mod-path "M:\path\dependency.mod"] [--output reference.md]
  hoi4skill build-clausewitz-library --game-root "C:\path\Hearts of Iron IV" [--code-mod-path "M:\path\explicitly-requested-mod"] [--request "literal user request"] [--output "C:\path\clausewitz-library"]
  hoi4skill query-clausewitz-library --query "communist national focus" [--system focus|event|idea|decision|character|history|scripted_effect] [--library "C:\path\clausewitz-library"] [--mod-library "C:\path\authorized-mod-library"] [--max-results 6]
  hoi4skill resolve-country-tag --text "给韩国制作国策" --game-root "C:\path\Hearts of Iron IV" [--tag KOR] [--source-root "M:\path\source_mod"] [--mod-path "M:\path\dependency.mod"] [--allow-new-tag] [--output tag_resolution.json]
  hoi4skill scan-mod-style "M:\path\mod" [--output mod_style.json] [--max-sprites 400]
  hoi4skill mod-knowledge "M:\path\mod" [--mod-path "M:\path\dependency.mod"] [--output mod_knowledge.json] [--max-items 80]
  hoi4skill build-mod-index "M:\path\mod" [--output mod_index.json] [--max-symbols 20000]
  hoi4skill query-symbol "M:\path\mod" --symbol RUS_duma_election [--kind focus|event|idea|decision|localisation|sprite] [--contains] [--max-results 50] [--output symbol.json]
  hoi4skill impact "M:\path\mod" [--symbol RUS_duma_election] [--changed common/national_focus/RUS.txt] [--max-symbols 80] [--max-references 200] [--output impact.json]
  hoi4skill reserve-id "M:\path\mod" --kind event --namespace rus [--count 10] [--output ids.json]
  hoi4skill reserve-id "M:\path\mod" --kind focus --tag RUS [--prefix RUS] [--count 10] [--output ids.json]
  hoi4skill check-namespace "M:\path\mod" [--namespace rus] [--output namespace.json]
  hoi4skill loc-audit "M:\path\mod" [--changed-only --changed localisation/simp_chinese/RUS.yml] [--max-items 200] [--output loc_audit.json]
  hoi4skill loc-sync-report "M:\path\mod" --from english --to simp_chinese [--max-items 200] [--output loc_sync.json]
  hoi4skill gfx-audit "M:\path\mod" [--changed-only --changed interface/RUS.gfx] [--max-items 200] [--output gfx_audit.json]
  hoi4skill logic-audit "M:\path\mod" [--changed-only --changed common/national_focus/RUS.txt] [--max-items 200] [--output logic_audit.json]
  hoi4skill asset-pack-plan --blueprint mod_blueprint.yml --package country_rus [--mod-root "M:\path\large_mod"] [--output assets.md]
  hoi4skill feature-context "M:\path\mod" [--tag RUS] [--system black_monday] [--max-symbols 120] [--max-references 120] [--output context.md]
  hoi4skill prepare-edit-context --input copy.txt --mod-root "M:\path\mod" --tag SOV --prefix sov_nep [--request "literal user request"] [--sheet FocusTree] [--game-root "C:\path\Hearts of Iron IV"] [--code-library "C:\path\clausewitz-library"] [--code-mod-path "M:\path\explicitly-requested-mod"] [--mod-path "M:\path\dependency.mod"] [--output edit_context.md]
  hoi4skill plan-history-edit "M:\path\mod" --text "给 GER 的 64 州加工厂" [--state-id 64] [--province-id 6521] [--capital 6521] [--game-root "C:\path\Hearts of Iron IV"] [--mod-path "M:\path\dependency.mod"] [--output history_plan.json]
  hoi4skill import-mod-ir "M:\path\mod" [--output imported_ir.json] [--max-items 1000]
  hoi4skill doctor-skill-install [--fix] [--root "C:\custom\skill-root"] [--keep "C:\path\hoi4-mod-maker"]
  hoi4skill focus-copy-prompt "M:\path\modA" ["M:\path\modB"] [--output focus_prompt.md] [--style full|compact]
  hoi4skill idea-copy-prompt "M:\path\modA" ["M:\path\modB"] [--output idea_prompt.md] [--style full|compact] [--all-categories]
  hoi4skill icon-preview --mod-root "M:\path\mod" [--output "M:\preview"] [--max-icons 800]
  hoi4skill register-gfx-icons --mod-root "M:\path\mod" --prefix sov_nep [--category all|dynamic|focus-idea|event|decision] [--output report.json]
  hoi4skill parse-focus-layout --input layout.txt --tag SOV --prefix sov_alt [--format json|focus-tree] [--mod-root "M:\path\mod"] [--game-root "C:\path\Hearts of Iron IV"] [--mod-path "M:\path\dependency.mod"] [--strict-code-index|--final-check] [--output plan.json]
  hoi4skill render-focus-code --input layout.txt --tag SOV --prefix sov_alt [--tree-id sov_focus] [--mod-root "M:\path\mod"] [--game-root "C:\path\Hearts of Iron IV"] [--mod-path "M:\path\dependency.mod"] [--strict-code-index|--final-check] [--output focus_tree.txt]
  hoi4skill apply-focus-layout --input layout.txt --mod-root "M:\path\mod" --tag SOV --prefix sov_alt [--game-root "C:\path\Hearts of Iron IV"] [--mod-path "M:\path\dependency.mod"] [--final-check]
  hoi4skill parse-focus-excel --input tree.xlsx --tag SOV --prefix sov_alt [--sheet FocusTree] [--format markdown|json|focus-tree] [--mod-root "M:\path\mod"] [--game-root "C:\path\Hearts of Iron IV"] [--mod-path "M:\path\dependency.mod"] [--strict-code-index|--final-check] [--output focus_review.md]
  hoi4skill apply-focus-excel --input tree.xlsx --mod-root "M:\path\mod" --tag SOV --prefix sov_alt [--sheet FocusTree] [--game-root "C:\path\Hearts of Iron IV"] [--mod-path "M:\path\dependency.mod"] [--final-check]
  hoi4skill parse-focus-copy-cards --input focus_copy.txt [--output focus_prompts.md]
  hoi4skill parse-feature-cards --input cards.txt --tag SOV --prefix sov_nep [--game-root "C:\path\Hearts of Iron IV"] [--mod-path "M:\path\dependency.mod"] [--strict-code-index|--final-check] [--output plan.json]
  hoi4skill apply-feature-cards --input cards.txt --mod-root "M:\path\mod" --tag SOV --prefix sov_nep [--game-root "C:\path\Hearts of Iron IV"] [--mod-path "M:\path\dependency.mod"] [--final-check]
  hoi4skill parse-event-cards --input events.txt --tag SOV --prefix sov_nep [--game-root "C:\path\Hearts of Iron IV"] [--mod-path "M:\path\dependency.mod"] [--strict-code-index|--final-check] [--output plan.json]
  hoi4skill apply-event-cards --input events.txt --mod-root "M:\path\mod" --tag SOV --prefix sov_nep [--game-root "C:\path\Hearts of Iron IV"] [--mod-path "M:\path\dependency.mod"] [--final-check]
  hoi4skill emit-hoi4yaml --input cards.txt --kind feature-cards|event-cards|focus-layout --tag SOV --prefix sov_nep [--game-root "C:\path\Hearts of Iron IV"] [--mod-path "M:\path\dependency.mod"] [--strict-code-index|--final-check] [--output mod.yaml]
  hoi4skill run-workflow --input copy.txt [--mod-root "M:\path\mod"] --tag SOV --prefix sov_nep [--request "literal user request"] [--sheet FocusTree] [--game-root "C:\path\Hearts of Iron IV"] [--mod-path "M:\path\dependency.mod"] [--dry-run] [--strict-code-index|--final-check] [--output workflow_report.json]
  hoi4skill generate-mod --text "给德国加一个国策，完成后获得3个军工厂" --output "M:\path\mod" --game-root "C:\path\Hearts of Iron IV" [--tag GER] [--prefix ger_demo] [--name "My Mod"] [--source-root "M:\path\source_mod"] [--mod-path "M:\path\dependency.mod"] [--strict-code-index|--final-check] [--report report.json]
  hoi4skill country-localisation-template --tag FER --name "远东铁路共和国" --prefix fer_rail [--output FER_l_simp_chinese.yml]
  hoi4skill translate-localisation --mod-root "M:\path\mod" --from <source_language> --to <target_language> [--format prompt|yml|json] [--output translated.md]
  hoi4skill translate-localisation --mod-root "M:\path\mod" --from french --to german --translated-input translated_l_german.yml --apply [--report loc_apply_report.json]
  hoi4skill analyze-error-log --input "%USERPROFILE%\Documents\Paradox Interactive\Hearts of Iron IV\logs\error.log" [--mod-root "M:\path\mod"] [--baseline old_error_report.json] [--changed-only --changed events/RUS.txt] [--output report.json]

This binary has no Python or PowerShell dependency.
"#,
        env!("CARGO_PKG_VERSION")
    );
}
